### ISSUE TITLE
Loading trained model.

### ISSUE THREAD

**Issue by quangtn266** [sauradip/SPOT#1]
Thank you for your great job.
I have one question about your trained model. I downloaded "TAGS_best.pth.tar" following your "Model inference" section. When I load the model for the inference, it conflicts to the architecture of the model. Could you explain it?

![Screen Shot 2023-01-10 at 21 02 10](https://user-images.githubusercontent.com/50879191/211571428-6d9dcf8a-9144-4565-b6a0-34eccf98914b.png)

**Comment by sauradip** [comment]
Hi @quangtn266 , 

Sorry for the error. I will correct the link in few days. This is a incorrect checkpoint
