### ISSUE TITLE
About spot_best_score.json file

### ISSUE THREAD

**Issue by lizhilin-ustc** [sauradip/SPOT#2]
Hi, I have some questions about your code. 
1) what is the role of "spot_best_score.json"? And where did these scores come from? These scores seem only used in the "multithread_detection" function, but these scores don't seem to do anything.
2) In spot_inference.py 133 lines, I can't find the "gsm_best_score.json" file, so I use "spot_best_score.json" to replace it.

**Comment by sauradip** [comment]
Hi ,
This score file is not used , you can ignore. This was obtained from the weakly supervised version of TAD model. But since we are not using all the videos , we cannot use this score for the score enhancement like BMN and GTAD

**Comment by lizhilin-ustc** [comment]
Thank you very much.
